# Generated by Django 4.2.6 on 2024-03-23 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gctrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersellorbuy',
            name='giftCardAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payment_images')),
                ('momo_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='gctrade.usersellorbuy')),
            ],
        ),
    ]
