# Generated by Django 4.2.6 on 2024-03-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gctrade', '0002_alter_usersellorbuy_giftcardamount_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='gctrade.profile'),
        ),
    ]
