# Generated by Django 4.2.6 on 2024-05-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctrade', '0003_alter_payments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='payments',
            name='image',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='momo_provider',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='ref',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
