# Generated by Django 4.2.6 on 2024-05-14 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gctrade', '0004_alter_payments_options_remove_payments_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField()),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('giftCardType', models.CharField(max_length=200)),
                ('otherGiftCardType', models.CharField(max_length=200)),
                ('giftCardAmount', models.PositiveBigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gctrade.profile')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
